name: Order Delivery Management System Backend Springboot

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ODMS 
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: Build project
      run: mvn clean install -DskipTests
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      run: docker build -t charlize367/order_backend .
    - name: Publish image to docker hub
      run: docker push charlize367/order_backend:latest

  deploy:
  needs: build
  runs-on: [self-hosted, backend]
  steps:
    - uses: actions/checkout@v4
    - name: Pull latest images
      run: docker compose -f ODMS/docker-compose.yml pull
    - name: Stop and remove old containers
      run: docker compose -f ODMS/docker-compose.yml down
    - name: Start all services
      run: docker compose -f ODMS/docker-compose.yml up -d --build


      
      
