name: Order Delivery Management System Backend Springboot

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ODMS 
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: Build project
      run: mvn clean install -DskipTests
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      run: docker build --build-arg AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' --build-arg AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' --build-arg FRONTEND_URL='${{ secrets.FRONTEND_URL }}' -t charlize367/order_backend .
    - name: Publish image to docker hub
      run: docker push charlize367/order_backend:latest

  deploy:
    needs: build
    runs-on: [self-hosted, backend]
    steps:
      - uses: actions/checkout@v4
      - name: Pull latest images
        run: docker compose -f ODMS/docker-compose.yml pull
      - name: Stop and remove old containers
        run: docker compose -f ODMS/docker-compose.yml down
      - name: Start all services
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        run: docker compose -f ODMS/docker-compose.yml up -d --build


      
      
