name: Order Delivery Management System Backend Springboot

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ODMS 
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: Build project
      run: mvn clean install -DskipTests
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      run: docker build -t charlize367/order_backend .
    - name: Publish image to docker hub
      run: docker push charlize367/order_backend:latest

  deploy:
    needs: build
    runs-on : [self-hosted, backend]
    defaults:
      run:
        working-directory: ODMS
    steps:
      - name: Pull image from docker hub
        run: docker pull charlize367/order_backend:latest
      - name: Delete old container
        run:  docker rm -f order-backend-container
      - name: Debug paths
        run: |
          pwd
          ls -R
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name order-backend-container charlize367/order_backend:latest
      - name: Deploy with Docker Compose
        run: |
          docker compose -f docker-compose.yml pull
          docker compose -f docker-compose.yml up -d --build

      
      
